### ISSUE TITLE
I think I need the passage2prop pkl file.

### ISSUE THREAD

**Issue by cody628** [TRUMANCFY/MixGR#1]
Hello. I have checked the uploaded code. I have a question. I think I need the passage2prop pkl file. Where can I download it? Or is it a file composed of chunk id and prop id?

**Comment by TRUMANCFY** [comment]
Hi, this is a file recording the mapping between passage and propositions, i,e., `{chunk_id : [prop_id, ....]}`. It can be generated from the datasets.

**Comment by cody628** [comment]
Thanks for the answer. I also have a question, what should I input for "retrieval_dir" in "fusion.sh"?

**Comment by TRUMANCFY** [comment]
This is the saving directory where the retrieval results for each granularity are saved.
